apiVersion: apps/v1
kind: Deployment
metadata:
  name: dc-gateteway-server
spec:
  replicas: 3
  selector:
    matchLabels:
      name: dc-gateteway-server
  template:
    metadata:
      labels:
        name: dc-gateteway-server
    spec:
      containers:
        - name: dc-gateteway-server
          image: dc-gateteway-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
            - containerPort: 4433
---
apiVersion: v1
kind: Service
metadata:
  name: dc-gateteway-server
spec:
  ports:
    - port: 8080
      name: "http"
      targetPort: 8080
      protocol: TCP
      nodePort: 30080
    - port: 4433
      name: "https"
      targetPort: 4433
      protocol: TCP
      nodePort: 30443
  type: NodePort
  selector:
    name: dc-gateteway-server